//! The model catalogue: rates, limits, and capabilities, sourced from models.dev.
//!
//! This replaces a hand-maintained price table. Hand-maintained rates go stale
//! silently — the table shipped without the Codex models for long enough that
//! every Codex generation derived with no cost at all, and nothing said so.
//!
//! The catalogue is a third kind of data in this system. It is not a raw capture,
//! and it is not a function of one: it is a cache of an external document. That
//! makes it the one thing here whose content can change without any call being
//! recorded, which is why every snapshot carries a digest and why pricing stamps
//! that digest onto the rows it prices.
//!
//! It is deliberately loaded into a process global. [`crate::derive::derive_one`]
//! is a pure function with no database handle, and pricing is called from inside
//! it; threading a catalogue down that path would mean giving the whole derive
//! chain a parameter it otherwise has no use for.

pub mod cache;
pub mod fetch;

use std::collections::HashMap;
use std::sync::{Arc, RwLock};

/// The catalogue shipped in the binary, so a fresh clone with no network still
/// prices. Regenerated by `orama catalog vendor`, never edited by hand — the
/// point of this module is to stop maintaining rates by hand.
const SEED: &[u8] = include_bytes!("../../assets/models.dev.json.gz");

/// Where the loaded snapshot came from. Shown in the UI so "my prices look old"
/// is answerable without guessing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// Embedded in the binary at build time.
    Embedded,
    /// Read from the local database.
    Cached,
    /// Fetched from models.dev during this run.
    Network,
}

impl Source {
    pub fn as_str(self) -> &'static str {
        match self {
            Source::Embedded => "embedded",
            Source::Cached => "cached",
            Source::Network => "network",
        }
    }
}

/// Identifies one catalogue payload.
#[derive(Debug, Clone)]
pub struct SnapshotMeta {
    /// Content hash of the payload. This is what pricing records, so a row can
    /// always be traced back to the rates that produced it.
    pub digest: String,
    pub etag: Option<String>,
    /// When this payload was downloaded.
    pub fetched_at: String,
    /// When it was last confirmed current — a 304 moves this and not `fetched_at`.
    pub checked_at: String,
    pub source: Source,
}

/// Per-million-token rates for one price band.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Rates {
    pub input: f64,
    pub output: f64,
    pub cache_read: Option<f64>,
    pub cache_write: Option<f64>,
}

/// A price band that applies above a context size.
#[derive(Debug, Clone, PartialEq)]
pub struct Tier {
    /// The band applies when context is strictly greater than this.
    pub over_context: i64,
    pub rates: Rates,
}

/// Rates plus any context-size bands above the base.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pricing {
    pub base: Rates,
    /// Sorted ascending by `over_context`.
    pub tiers: Vec<Tier>,
}

impl Pricing {
    /// The rates that apply at this context size.
    ///
    /// The boundary is exclusive: models.dev mirrors a single tier into a legacy
    /// `context_over_200k` field, and upstream names the tier value a `size` that
    /// the band sits above, so a prompt exactly at the size pays the base rate.
    pub fn at_context(&self, context_tokens: i64) -> &Rates {
        // Tiers are ascending, so the last one the context exceeds is the band.
        self.tiers
            .iter()
            .rfind(|tier| context_tokens > tier.over_context)
            .map(|tier| &tier.rates)
            .unwrap_or(&self.base)
    }
}

/// Token ceilings. All optional — a model that never published one reports
/// nothing rather than a zero.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Limits {
    pub context: Option<i64>,
    pub input: Option<i64>,
    pub output: Option<i64>,
}

/// What the model can do.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Capabilities {
    pub reasoning: bool,
    pub tool_call: bool,
    pub structured_output: bool,
    pub attachment: bool,
    pub open_weights: bool,
    pub input_modalities: Vec<String>,
    pub output_modalities: Vec<String>,
}

/// One model as the catalogue describes it.
#[derive(Debug, Clone)]
pub struct ModelRecord {
    pub provider: String,
    pub id: String,
    pub name: String,
    pub family: Option<String>,
    pub description: Option<String>,
    pub release_date: Option<String>,
    pub knowledge: Option<String>,
    pub status: Option<String>,
    /// Absent for models the catalogue lists without rates. Absent is not free.
    pub pricing: Option<Pricing>,
    pub limits: Limits,
    pub capabilities: Capabilities,
}

/// A parsed catalogue payload.
#[derive(Debug)]
pub struct Catalog {
    pub snapshot: SnapshotMeta,
    providers: HashMap<String, HashMap<String, ModelRecord>>,
}

impl Catalog {
    /// Find the record for a model served by a provider.
    ///
    /// Only two things resolve: an exact id, and an exact id after stripping a
    /// suffix that providers document as naming the same model — a dated
    /// snapshot (`claude-opus-5-20260115`) or a moving `-latest` alias.
    ///
    /// Notably **not** longest-prefix matching, which the hand-maintained table
    /// used and which does not survive contact with a full catalogue. 1,568 ids
    /// here have a shorter sibling that prefixes them, and 926 of those are
    /// priced differently from that sibling — `gpt-4o` would resolve to `gpt-4`
    /// and bill at $30 instead of $2.50, and `gpt-5.6-luna` to `gpt-5.6` at five
    /// times its real rate. An unpriced call is a visible gap; a call priced 12×
    /// wrong is a confident wrong answer that nothing catches.
    ///
    /// Resolution is provider-scoped because the same id is sold by up to
    /// eleven providers at six different prices. Only an exact id is trusted
    /// from a provider other than the one the call was captured under.
    pub fn resolve(&self, provider: &str, model: &str) -> Option<&ModelRecord> {
        if let Some(models) = self.providers.get(provider) {
            if let Some(found) = models.get(model) {
                return Some(found);
            }
            if let Some(base) = strip_alias(model) {
                if let Some(found) = models.get(base) {
                    return Some(found);
                }
            }
        }
        self.providers
            .iter()
            .filter(|(name, _)| name.as_str() != provider)
            .find_map(|(_, models)| models.get(model))
    }

    pub fn provider_count(&self) -> usize {
        self.providers.len()
    }

    pub fn model_count(&self) -> usize {
        self.providers.values().map(HashMap::len).sum()
    }
}

/// Strip a suffix that names the same model under a different label.
///
/// Only two forms, both conventions the providers themselves document: a build
/// date (`-20251001`) and a moving alias (`-latest`). Anything else is a
/// different model until proven otherwise.
fn strip_alias(model: &str) -> Option<&str> {
    if let Some(base) = model.strip_suffix("-latest") {
        return Some(base);
    }
    let (base, tail) = model.rsplit_once('-')?;
    (tail.len() == 8 && tail.bytes().all(|byte| byte.is_ascii_digit())).then_some(base)
}

/// The catalogue in force for this process.
///
/// A plain `RwLock` rather than a channel or a handle passed around: readers are
/// on the blocking derive thread, the writer is an async refresh task, and the
/// read clones an `Arc` and drops the guard immediately, so no lock is ever held
/// across an await.
static CATALOG: RwLock<Option<Arc<Catalog>>> = RwLock::new(None);

/// The catalogue currently in force, if one has been installed.
pub fn current() -> Option<Arc<Catalog>> {
    CATALOG.read().ok().and_then(|guard| guard.clone())
}

/// Replace the catalogue in force.
pub fn install(catalog: Arc<Catalog>) {
    if let Ok(mut guard) = CATALOG.write() {
        *guard = Some(catalog);
    }
}

/// Parse the catalogue embedded in the binary.
pub fn embedded() -> anyhow::Result<Catalog> {
    let json = ungzip(SEED)?;
    parse(&json, None, Source::Embedded)
}

/// Load the best catalogue available without touching the network: the cached
/// snapshot if the database has one, the embedded seed otherwise.
///
/// Never fails the caller. A catalogue that cannot be loaded leaves pricing
/// reporting nothing, which is the honest answer — reporting zero would not be.
pub fn load_offline(conn: &rusqlite::Connection) -> Option<Arc<Catalog>> {
    match cache::read(conn) {
        Ok(Some(catalog)) => return Some(Arc::new(catalog)),
        Ok(None) => {}
        Err(err) => eprintln!("orama: could not read the cached model catalogue: {err}"),
    }
    match embedded() {
        Ok(catalog) => Some(Arc::new(catalog)),
        Err(err) => {
            eprintln!("orama: could not load the embedded model catalogue: {err}");
            None
        }
    }
}

/// Install the best offline catalogue, if none is installed yet.
pub fn ensure_loaded(conn: &rusqlite::Connection) {
    if current().is_some() {
        return;
    }
    if let Some(catalog) = load_offline(conn) {
        install(catalog);
    }
}

pub(crate) fn ungzip(bytes: &[u8]) -> anyhow::Result<Vec<u8>> {
    use std::io::Read;
    let mut out = Vec::new();
    flate2::read::GzDecoder::new(bytes).read_to_end(&mut out)?;
    Ok(out)
}

/// Compress a payload for the bundled seed.
///
/// Exposed for `orama catalog vendor`, which is the only supported way to
/// produce that file — the seed is a verbatim copy of what models.dev served,
/// and nothing between the wire and the disk is allowed to reinterpret it.
pub fn gzip_for_seed(payload: &[u8]) -> anyhow::Result<Vec<u8>> {
    gzip(payload)
}

pub(crate) fn gzip(bytes: &[u8]) -> anyhow::Result<Vec<u8>> {
    use std::io::Write;
    let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
    encoder.write_all(bytes)?;
    Ok(encoder.finish()?)
}

/// Parse a models.dev `api.json` payload.
///
/// The document is an object keyed by provider id, each with a `models` object.
/// Every field below `id` is optional in practice, so nothing here fails the
/// parse for a missing key — a model with no `cost` block is a model whose price
/// is unknown, not a malformed document.
pub fn parse(payload: &[u8], etag: Option<String>, source: Source) -> anyhow::Result<Catalog> {
    let root: serde_json::Value = serde_json::from_slice(payload)?;
    let object = root
        .as_object()
        .ok_or_else(|| anyhow::anyhow!("catalogue root is not an object"))?;

    let mut providers = HashMap::new();
    for (provider_id, provider) in object {
        let Some(models) = provider.get("models").and_then(|m| m.as_object()) else {
            continue;
        };
        let mut parsed = HashMap::new();
        for (model_id, model) in models {
            parsed.insert(model_id.clone(), parse_model(provider_id, model_id, model));
        }
        if !parsed.is_empty() {
            providers.insert(provider_id.clone(), parsed);
        }
    }

    if providers.is_empty() {
        anyhow::bail!("catalogue contains no models");
    }

    let now = crate::util::now_rfc3339();
    Ok(Catalog {
        snapshot: SnapshotMeta {
            digest: blake3::hash(payload).to_hex().to_string(),
            etag,
            fetched_at: now.clone(),
            checked_at: now,
            source,
        },
        providers,
    })
}

fn parse_model(provider: &str, id: &str, model: &serde_json::Value) -> ModelRecord {
    let text = |key: &str| model.get(key).and_then(|v| v.as_str()).map(str::to_owned);
    let flag = |key: &str| model.get(key).and_then(|v| v.as_bool()).unwrap_or(false);
    let modality = |key: &str| {
        model
            .get("modalities")
            .and_then(|m| m.get(key))
            .and_then(|v| v.as_array())
            .map(|items| {
                items
                    .iter()
                    .filter_map(|item| item.as_str().map(str::to_owned))
                    .collect()
            })
            .unwrap_or_default()
    };
    let limit = |key: &str| model.get("limit").and_then(|l| l.get(key)).and_then(as_i64);

    ModelRecord {
        provider: provider.to_owned(),
        id: id.to_owned(),
        name: text("name").unwrap_or_else(|| id.to_owned()),
        family: text("family"),
        description: text("description"),
        release_date: text("release_date"),
        knowledge: text("knowledge"),
        status: text("status"),
        pricing: model.get("cost").and_then(parse_pricing),
        limits: Limits {
            context: limit("context"),
            input: limit("input"),
            output: limit("output"),
        },
        capabilities: Capabilities {
            reasoning: flag("reasoning"),
            tool_call: flag("tool_call"),
            structured_output: flag("structured_output"),
            attachment: flag("attachment"),
            open_weights: flag("open_weights"),
            input_modalities: modality("input"),
            output_modalities: modality("output"),
        },
    }
}

fn parse_pricing(cost: &serde_json::Value) -> Option<Pricing> {
    let base = parse_rates(cost)?;
    let mut tiers: Vec<Tier> = cost
        .get("tiers")
        .and_then(|t| t.as_array())
        .map(|items| {
            items
                .iter()
                .filter_map(|item| {
                    let over_context = item
                        .get("tier")
                        .and_then(|t| t.get("size"))
                        .and_then(as_i64)?;
                    Some(Tier {
                        over_context,
                        rates: parse_rates(item)?,
                    })
                })
                .collect()
        })
        .unwrap_or_default();
    tiers.sort_by_key(|tier| tier.over_context);
    Some(Pricing { base, tiers })
}

fn parse_rates(value: &serde_json::Value) -> Option<Rates> {
    let number = |key: &str| value.get(key).and_then(serde_json::Value::as_f64);
    // A band with no input rate prices nothing; treat it as absent rather than
    // inventing a zero.
    Some(Rates {
        input: number("input")?,
        output: number("output").unwrap_or(0.0),
        cache_read: number("cache_read"),
        cache_write: number("cache_write"),
    })
}

fn as_i64(value: &serde_json::Value) -> Option<i64> {
    value
        .as_i64()
        .or_else(|| value.as_f64().map(|number| number as i64))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> Catalog {
        let payload = br#"{
            "anthropic": { "models": {
                "claude-opus-5": { "id": "claude-opus-5", "name": "Claude Opus 5",
                    "family": "claude-opus", "reasoning": true, "tool_call": true,
                    "modalities": {"input":["text","image"],"output":["text"]},
                    "limit": {"context": 1000000, "output": 128000},
                    "cost": {"input":5,"output":25,"cache_read":0.5,"cache_write":6.25} },
                "claude-haiku-4-5-20251001": { "id": "claude-haiku-4-5-20251001",
                    "limit": {"context": 200000},
                    "cost": {"input":1,"output":5} }
            }},
            "openai": { "models": {
                "gpt-5.6-luna": { "id": "gpt-5.6-luna", "name": "GPT-5.6 Luna",
                    "limit": {"context": 1050000, "input": 922000, "output": 128000},
                    "cost": {"input":1,"output":6,"cache_read":0.1,"cache_write":1.25,
                             "tiers":[{"input":2,"output":9,"cache_read":0.2,
                                       "cache_write":2.5,"tier":{"type":"context","size":272000}}]} },
                "gpt-image-1": { "id": "gpt-image-1" }
            }}
        }"#;
        parse(payload, None, Source::Embedded).unwrap()
    }

    #[test]
    fn an_exact_id_resolves_within_its_provider() {
        let catalog = fixture();
        let found = catalog.resolve("anthropic", "claude-opus-5").unwrap();
        assert_eq!(found.id, "claude-opus-5");
        assert_eq!(found.pricing.as_ref().unwrap().base.input, 5.0);
        assert_eq!(found.limits.context, Some(1_000_000));
        assert!(found.capabilities.tool_call);
    }

    #[test]
    fn a_dated_snapshot_falls_back_to_its_family() {
        let catalog = fixture();
        // The catalogue does not carry this exact build, but it carries the
        // family, and a trailing build date names the same model.
        let found = catalog
            .resolve("anthropic", "claude-opus-5-20260115")
            .unwrap();
        assert_eq!(found.id, "claude-opus-5");
    }

    #[test]
    fn a_variant_suffix_does_not_resolve_to_its_base() {
        let catalog = fixture();
        // The regression guard for the rule this replaced. `gpt-5.6-luna` is a
        // fifth the price of `gpt-5.6`, and `gpt-4o` is a twelfth the price of
        // `gpt-4` — across the real catalogue, 926 ids are priced differently
        // from the shorter sibling that prefixes them. Reporting nothing is the
        // only honest answer for a variant we do not have rates for.
        assert!(catalog.resolve("openai", "gpt-5.6-luna-preview").is_none());
        assert!(catalog.resolve("openai", "gpt-5.6-codex").is_none());
    }

    #[test]
    fn a_lookup_is_scoped_to_its_provider() {
        let catalog = fixture();
        // The same id is sold by many providers at different prices, so a call
        // captured as Anthropic is never priced from an OpenAI entry by way of
        // a near-miss.
        assert!(catalog
            .resolve("anthropic", "gpt-5.6-luna-20260709")
            .is_none());
        assert!(catalog.resolve("openai", "gpt-5.6-luna-20260709").is_some());
    }

    #[test]
    fn an_exact_id_is_still_found_under_the_wrong_provider() {
        let catalog = fixture();
        // Dialect detection reports `unknown` for third-party hosts; an exact id
        // is specific enough to trust.
        let found = catalog.resolve("unknown", "gpt-5.6-luna").unwrap();
        assert_eq!(found.provider, "openai");
    }

    #[test]
    fn an_absent_model_resolves_to_nothing() {
        let catalog = fixture();
        assert!(catalog.resolve("anthropic", "claude-mythos-5").is_none());
    }

    #[test]
    fn a_model_listed_without_rates_has_no_pricing() {
        let catalog = fixture();
        // Absent is not free.
        let found = catalog.resolve("openai", "gpt-image-1").unwrap();
        assert!(found.pricing.is_none());
    }

    #[test]
    fn a_context_tier_applies_only_above_its_size() {
        let catalog = fixture();
        let pricing = catalog
            .resolve("openai", "gpt-5.6-luna")
            .unwrap()
            .pricing
            .as_ref()
            .unwrap();
        assert_eq!(pricing.at_context(271_999).input, 1.0);
        // The boundary itself is still the base band.
        assert_eq!(pricing.at_context(272_000).input, 1.0);
        assert_eq!(pricing.at_context(272_001).input, 2.0);
    }

    #[test]
    fn the_embedded_seed_parses_and_covers_the_models_we_capture() {
        let catalog = embedded().unwrap();
        // The seed is a generated artifact; if it ever ships empty or truncated
        // this is the test that says so.
        assert!(catalog.model_count() > 1000);
        for (provider, model) in [
            ("anthropic", "claude-opus-5"),
            ("anthropic", "claude-sonnet-5"),
            ("openai", "gpt-5.6-luna"),
            ("openai", "gpt-5.6-terra"),
        ] {
            assert!(
                catalog.resolve(provider, model).is_some(),
                "seed is missing {provider}/{model}"
            );
        }
    }
}
