[package]
name = "orama-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "orama"
path = "src/main.rs"

[dependencies]
orama-core = { path = "../core" }
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
